package com.jason.manongapp.index.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jason.manongapp.index.db.DateDao;

import com.jason.manongapp.index.db.DateDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dateDaoDaoConfig;

    private final DateDaoDao dateDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dateDaoDaoConfig = daoConfigMap.get(DateDaoDao.class).clone();
        dateDaoDaoConfig.initIdentityScope(type);

        dateDaoDao = new DateDaoDao(dateDaoDaoConfig, this);

        registerDao(DateDao.class, dateDaoDao);
    }
    
    public void clear() {
        dateDaoDaoConfig.clearIdentityScope();
    }

    public DateDaoDao getDateDaoDao() {
        return dateDaoDao;
    }

}
