package com.jason.manongapp.index.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "index_date".
*/
public class DateDaoDao extends AbstractDao<DateDao, Void> {

    public static final String TABLENAME = "index_date";

    /**
     * Properties of entity DateDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DateString = new Property(0, String.class, "dateString", false, "date_string");
    }


    public DateDaoDao(DaoConfig config) {
        super(config);
    }
    
    public DateDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"index_date\" (" + //
                "\"date_string\" TEXT);"); // 0: dateString
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"index_date\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DateDao entity) {
        stmt.clearBindings();
 
        String dateString = entity.getDateString();
        if (dateString != null) {
            stmt.bindString(1, dateString);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DateDao entity) {
        stmt.clearBindings();
 
        String dateString = entity.getDateString();
        if (dateString != null) {
            stmt.bindString(1, dateString);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DateDao readEntity(Cursor cursor, int offset) {
        DateDao entity = new DateDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // dateString
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DateDao entity, int offset) {
        entity.setDateString(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DateDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DateDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(DateDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
